FROM ubuntu


RUN apt-get update && apt-get -y install python3.7
RUN apt-get install -y pip


RUN mkdir -p /code_base/airflow/dags

RUN export AIRFLOW_HOME=/code_base/airflow

RUN AIRFLOW_VERSION=2.1.2
RUN python3 --version

RUN pip install "apache-airflow==2.1.2" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.1.2/constraints-no-providers-3.7.txt"


RUN airflow db init
RUN airflow users  create --role Admin --username admin --email admin --firstname admin --lastname admin --password admin


RUN pip install psycopg2-binary
RUN pip install pandas

ENTRYPOINT airflow scheduler

